### ISSUE TITLE
Doesn't work with serverless 1.16.1

### ISSUE THREAD

**Issue by sokoow** [ocadotechnology/hippolyte#3] opened 2017-06-30 09:30 UTC
I may be doing something st00pid, but it doesn't work for me:

```
serverless deploy --region eu-west-1 --stage dev --email bazinga@test.com

 Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:provisioner.region' could not be found.


 Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:provisioner.stage' could not be found.


  Serverless Error ---------------------------------------

  Trying to populate non string value into a string for variable ${self:provisioner.region}. Please make sure the value of the property is a string.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.1.3
     Serverless Version:     1.16.1
```

**Comment by sokoow** [comment] 2017-06-30 09:31
may be somehow related to https://github.com/serverless/serverless/issues/3049

**Comment by Mavus** [comment] 2017-06-30 12:31
Thanks for reporting the issue. I've just pushed a change that should resolve this. `region`, `stage` and `email` should all work correctly as cmd line args now.

**Comment by sokoow** [comment] 2017-06-30 12:50
It's a bit better, now I'm getting this with same command line:
```
  Serverless Error ---------------------------------------

  An error occurred while provisioning your stack: EmailNotificationTopic - Invalid parameter: Email address.
```

**Comment by Mavus** [comment] 2017-06-30 13:37
This looks like it was the email variable in `serverless.yaml` not being correctly substituted in the cloudformation template. I've pushed a commit and done deployment to test this
```
serverless deploy --stage prod --region eu-west-1 --email foo@bar.com
Serverless: Installing required Python packages for runtime python2.7...
Serverless: Linking required Python packages...
Serverless: Packaging service...
Serverless: Unlinking required Python packages...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (1.72 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.................................
Serverless: Stack update finished...
Service Information
service: hippolyte
stage: prod
region: eu-west-1
api keys:
  None
endpoints:
  None
functions:
  backup: hippolyte-prod-backup
```
I'm on a slightly older serverless version
```
Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.11.0
     Serverless Version: 1.14.0
```
So I'll upgrade and prove it still works there too. Let me know if that resolves your issue.

**Comment by Mavus** [comment] 2017-07-03 21:47
I've tested this with the latest version and looks to building successfully now.
```
$ sls -v
1.16.1
$  sls deploy --stage prod --region eu-west-1 --email foo@bar.com --noDeploy
Serverless: Installing required Python packages for runtime python2.7...
Serverless: Linking required Python packages...
Serverless: Packaging service...
Serverless: Unlinking required Python packages...
```

**Comment by RomekRJM** [comment] 2017-07-03 22:28
After upgrading to serverless 1.16.1 I can now reproduce this problem. I'm able to fix it, by changing email reference to: `Resource: "arn:aws:sns:${self:provider.region}:${AWS::AccountId}:hippolyte-backup-monitoring"`. However, I'm now getting a new error: ` Unexpected token {`. @Mavus let's take a closer look tomorrow.
@sokoow many thanks for the bug report. Can you try with serverless 1.14.0 in the mean time? We are very interested in having someone from outside of ocado to test it.

**Comment by RomekRJM** [comment] 2017-07-04 10:01
In my case problem was with using to old Node.js version. We've verified with @Mavus , that it works with: Node.js 6.11 / Serverless 1.16.1 / serverless-python-requirements 2.3.3 . I have put it in our readme. @sokoow can you try again and verify if it now works for you?

**Comment by RomekRJM** [comment] 2017-07-06 10:27
I'm closing it, as we've proven that it now works. As part of the task we've added serverless.yaml verification to travis build, to make sure we will not have the same problems again.

**Closed as completed by RomekRJM** 2017-07-06 10:27 UTC
Labels: bug
